name: colibri
description: Colibri

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # for functional programming
  dartz: ^0.9.1
  # for api calls
  dio: ^3.0.10
  # Goolge fonts
  google_fonts: 1.1.0
  flutter_hooks: ^0.14.0
  auto_route: 0.6.9
  flutter_screenutil: 3.0.2
  rxdart: ^0.23.1
  flutter_svg: ^0.18.1
  flutter_bloc: ^6.0.5
  freezed: ^0.12.1
  freezed_annotation:
  equatable: ^1.2.5
  injectable: ^1.0.5
  get_it: ^5.0.1
  flushbar: ^1.10.4
  flutter_webview_plugin: ^0.3.11
  font_awesome_flutter: ^8.8.1
  cached_network_image: ^2.3.3
  image_picker: ^0.6.7+14
  emoji_picker: ^0.1.0
  flutter_animated_dialog: ^1.1.0
  giphy_picker: ^1.0.6
  flutter_secure_storage: ^3.3.4
  material_floating_search_bar: ^0.1.7
  intl: ^0.16.1
  carousel_slider: ^2.3.1
  video_thumbnail: 0.1.6
  video_player: 0.11.0
  photo_view: ^0.10.2
  velocity_x: ^1.0.1
  fluttertoast: ^7.1.5
#  flutter_vlc_player: ^4.0.2
#  file_picker: 2.0.10
#  photo: ^0.4.8
  wechat_assets_picker: ^4.2.2
  thumbnails: ^1.0.1
  path_provider: ^1.6.24
  video_compress: ^2.1.0
  flutter_easyloading: ^2.0.1
  permission_handler: ^5.0.1+1
  better_player: ^0.0.35
  awesome_dialog: ^1.2.1
  flutter_facebook_login: ^3.0.0
  google_sign_in: ^4.5.6
#  flutter_twitter_login: ^1.1.0
  twitter_login: ^2.1.0
  i18n_extension: ^1.4.2
  easy_localization:
  infinite_scroll_pagination: ^2.2.2
  flutter_native_splash: ^0.1.9
  dotted_border: ^1.0.7
  flutter_staggered_grid_view: ^0.3.2
  alphabet_list_scroll_view: ^1.0.6
  flutter_slidable: ^0.5.7
  faker: ^1.3.0
  azlistview: ^1.0.2
  lpinyin: ^1.1.0
  overlay: ^0.0.1
  url_launcher: ^5.7.10
  flutter_keyboard_visibility: ^4.0.0
  webview_flutter: ^1.0.7
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^0.6.9
  build_runner:
  injectable_generator: ^1.0.5
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - data/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Avenir
      fonts:
        - asset: fonts/AvenirNextLTPro-Light.ttf
          weight: 200
        - asset: fonts/AvenirNextLTPro-Regular.ttf
          weight: 400
        - asset: fonts/AvenirNextLTPro-Heavy.ttf
          weight: 600
#        - asset: fonts/AvenirNextLTPro-Bold.ttf
#          weight: 700



  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
